name = "PEtabSciMLTestsuite"
version = "1.0.0"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
ComponentArrays = "b0b7db55-cfe3-40fc-9ded-d10e2dbeff66"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
FiniteDifferences = "26cc04aa-876d-5657-8c51-4c34ba976000"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
Lux = "b2108857-7c20-44ae-9111-449ecde12c47"
OrdinaryDiffEqVerner = "79d7bb75-1356-48c1-b8c0-6832512096c2"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
SimpleUnPack = "ce78b400-467f-4804-87d8-8f486da07d0a"
StableRNGs = "860ef19b-820b-49d6-a774-d7a799459cd3"
YAML = "ddb6d928-2868-570f-bddf-ab3f9cf99eb6"
